### ISSUE TITLE
Support Configfs-tsm introduced since kernel 6.7 for attestation report fetching in TEE environments

### ISSUE THREAD

**Issue by Ruoyu-y** [cc-api/cc-trusted-vmsdk#48]
An attestation report is signed evidence of how a Trusted Virtual Machine (TVM) was launched and its current state. A verifying party uses the report to make judgements of the confidentiality and integrity of that execution environment. Upon successful attestation the verifying party may, for example, proceed to deploy secrets to the TVM to carry out a workload. Multiple confidential computing platforms share this similar flow.
Since kernel 6.7, configfs has been leveraged as a common approach to fetch the attestation report for maintainability compared to ioctl(), and for its scalability compared to sysfs. Atomicity can be enforced at item creation time, and a conflict detection mechanism is included for scenarios where multiple threads may share a single configuration instance.
vmsdk shall support this approach for attestation fetching also.

**Comment by Ruoyu-y** [comment]
#40, #38 and #37 are added for the purpose to support the flow.

**Comment by ruomengh** [comment]
Thanks @Ruoyu-y for addressing the issue! Close it as complete.
